// Mock vehicle data for Mikki Trade Motors

export interface Vehicle {
  id: string;
  make: string;
  model: string;
  year: number;
  price: number;
  oldPrice?: number;
  mileage: string;
  transmission: string;
  fuelType: string;
  bodyType: string;
  color: string;
  condition: string;
  location: string;
  images: string[];
  badges?: ('NEW' | 'HOT DEAL' | 'LIMITED')[];
  isSaved?: boolean;
  featured?: boolean;
  tagline?: string;
  features: string[];
  description: string;
  engineSize: string;
  drivetrain: string;
  seats: number;
  doors: number;
  createdAt: string;
}

const generateVehicleImages = (make: string, model: string, count: number = 5): string[] => {
  // Using placeholder car images with proper URLs
  // These will fall back to the SVG placeholders created in VehicleCard and HeroCarousel
  const baseUrls = [
    'https://images.unsplash.com/photo-1494976388531-d1058494cdd8', // Luxury car
    'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf', // Sports car
    'https://images.unsplash.com/photo-1469285994282-454ceb49e1f9', // SUV
    'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2', // Modern car
    'https://images.unsplash.com/photo-1503376780353-7e6692767b70', // Classic car
    'https://images.unsplash.com/photo-1552519507-da3b142c6e3d', // Sedan
  ];

  return Array.from({ length: count }, (_, i) =>
    `${baseUrls[i % baseUrls.length]}?w=800&h=600&fit=crop&q=80`
  );
};

export const mockVehicles: Vehicle[] = [
  // Featured Vehicles
  {
    id: 'v001',
    make: 'Mercedes-Benz',
    model: 'G-Class G63 AMG',
    year: 2024,
    price: 18500000,
    oldPrice: 21000000,
    mileage: '5,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Black',
    condition: 'Brand New',
    location: 'Nairobi',
    images: generateVehicleImages('Mercedes', 'G-Class', 6),
    badges: ['HOT DEAL', 'LIMITED'],
    featured: true,
    tagline: 'Ultimate Luxury Performance SUV',
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Parking Sensors', 'LED Headlights', 'Heated Seats', 'Keyless Entry', 'Alloy Wheels', 'Cruise Control'],
    description: 'Experience the pinnacle of luxury and performance with this brand new Mercedes-Benz G63 AMG. Featuring a powerful V8 engine, premium leather interior, and advanced safety features.',
    engineSize: '4.0L V8 Twin-Turbo',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-12-20',
  },
  {
    id: 'v002',
    make: 'Toyota',
    model: 'Land Cruiser V8',
    year: 2024,
    price: 12800000,
    oldPrice: 14500000,
    mileage: '3,200 km',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    bodyType: 'SUV',
    color: 'White',
    condition: 'Brand New',
    location: 'Mombasa',
    images: generateVehicleImages('Toyota', 'Land-Cruiser', 6),
    badges: ['NEW', 'HOT DEAL'],
    featured: true,
    tagline: 'The Legend Continues',
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Parking Sensors', 'Cruise Control', 'Alloy Wheels', 'LED Headlights'],
    description: 'The iconic Toyota Land Cruiser V8, renowned for its legendary reliability and off-road capability. Perfect for both urban luxury and adventure.',
    engineSize: '4.5L V8 Diesel',
    drivetrain: '4WD',
    seats: 7,
    doors: 4,
    createdAt: '2024-12-19',
  },
  {
    id: 'v003',
    make: 'BMW',
    model: 'X7 xDrive40i',
    year: 2024,
    price: 15200000,
    mileage: '1,800 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Silver',
    condition: 'Brand New',
    location: 'Nairobi',
    images: generateVehicleImages('BMW', 'X7', 5),
    badges: ['NEW'],
    featured: true,
    tagline: 'Elegance Meets Power',
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Parking Sensors', 'Heated Seats', 'Bluetooth', 'Cruise Control', 'LED Headlights', 'Alloy Wheels', 'Keyless Entry'],
    description: 'BMW X7 combines luxury, space, and performance. Features the latest BMW technology and premium materials throughout.',
    engineSize: '3.0L Inline-6 Turbo',
    drivetrain: 'AWD',
    seats: 7,
    doors: 4,
    createdAt: '2024-12-18',
  },

  // Toyota Lineup
  {
    id: 'v004',
    make: 'Toyota',
    model: 'Prado TX',
    year: 2023,
    price: 6500000,
    mileage: '15,000 km',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    bodyType: 'SUV',
    color: 'Gray',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Toyota', 'Prado', 4),
    features: ['Leather Seats', 'Navigation System', 'Backup Camera', 'Alloy Wheels', 'Cruise Control'],
    description: 'Well-maintained Toyota Prado TX with low mileage. Excellent condition, perfect family SUV.',
    engineSize: '2.8L Diesel',
    drivetrain: '4WD',
    seats: 7,
    doors: 4,
    createdAt: '2024-12-17',
  },
  {
    id: 'v005',
    make: 'Toyota',
    model: 'Fortuner 2.8 GD-6',
    year: 2023,
    price: 5200000,
    mileage: '22,000 km',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    bodyType: 'SUV',
    color: 'White',
    condition: 'Foreign Used',
    location: 'Kisumu',
    images: generateVehicleImages('Toyota', 'Fortuner', 4),
    features: ['Backup Camera', 'Alloy Wheels', 'Bluetooth', 'Cruise Control'],
    description: 'Reliable and powerful Toyota Fortuner. Perfect for Kenyan roads and family adventures.',
    engineSize: '2.8L Diesel',
    drivetrain: '4WD',
    seats: 7,
    doors: 4,
    createdAt: '2024-12-16',
  },
  {
    id: 'v006',
    make: 'Toyota',
    model: 'Harrier Hybrid',
    year: 2022,
    price: 4800000,
    mileage: '35,000 km',
    transmission: 'CVT',
    fuelType: 'Hybrid',
    bodyType: 'SUV',
    color: 'Black',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Toyota', 'Harrier', 4),
    badges: ['HOT DEAL'],
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights'],
    description: 'Fuel-efficient Toyota Harrier Hybrid with modern features and excellent fuel economy.',
    engineSize: '2.5L Hybrid',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-12-15',
  },
  {
    id: 'v007',
    make: 'Toyota',
    model: 'RAV4 Adventure',
    year: 2023,
    price: 5500000,
    mileage: '18,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Blue',
    condition: 'Foreign Used',
    location: 'Nakuru',
    images: generateVehicleImages('Toyota', 'RAV4', 4),
    features: ['Sunroof', 'Navigation System', 'Backup Camera', 'Alloy Wheels', 'Cruise Control'],
    description: 'Adventure-ready RAV4 with modern safety features and comfortable interior.',
    engineSize: '2.5L',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-12-14',
  },

  // Nissan Lineup
  {
    id: 'v008',
    make: 'Nissan',
    model: 'Patrol V8',
    year: 2023,
    price: 9500000,
    mileage: '12,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'White',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Nissan', 'Patrol', 5),
    badges: ['LIMITED'],
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Parking Sensors', 'Cruise Control'],
    description: 'Powerful Nissan Patrol V8 with luxurious interior and exceptional off-road capability.',
    engineSize: '5.6L V8',
    drivetrain: '4WD',
    seats: 7,
    doors: 4,
    createdAt: '2024-12-13',
  },
  {
    id: 'v009',
    make: 'Nissan',
    model: 'X-Trail',
    year: 2022,
    price: 3800000,
    mileage: '28,000 km',
    transmission: 'CVT',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Silver',
    condition: 'Foreign Used',
    location: 'Mombasa',
    images: generateVehicleImages('Nissan', 'X-Trail', 4),
    features: ['Navigation System', 'Backup Camera', 'Alloy Wheels', 'Bluetooth'],
    description: 'Versatile Nissan X-Trail with excellent fuel economy and spacious interior.',
    engineSize: '2.0L',
    drivetrain: 'AWD',
    seats: 7,
    doors: 4,
    createdAt: '2024-12-12',
  },

  // Honda Lineup
  {
    id: 'v010',
    make: 'Honda',
    model: 'CR-V Touring',
    year: 2023,
    price: 5800000,
    mileage: '14,000 km',
    transmission: 'CVT',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Red',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Honda', 'CR-V', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Heated Seats'],
    description: 'Premium Honda CR-V Touring with advanced safety features and comfortable ride.',
    engineSize: '1.5L Turbo',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-12-11',
  },
  {
    id: 'v011',
    make: 'Honda',
    model: 'Vezel Hybrid',
    year: 2021,
    price: 3200000,
    mileage: '42,000 km',
    transmission: 'CVT',
    fuelType: 'Hybrid',
    bodyType: 'SUV',
    color: 'White',
    condition: 'Foreign Used',
    location: 'Eldoret',
    images: generateVehicleImages('Honda', 'Vezel', 4),
    features: ['Navigation System', 'Backup Camera', 'LED Headlights', 'Alloy Wheels'],
    description: 'Efficient Honda Vezel Hybrid, perfect for city driving with great fuel economy.',
    engineSize: '1.5L Hybrid',
    drivetrain: 'FWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-12-10',
  },

  // Mazda Lineup
  {
    id: 'v012',
    make: 'Mazda',
    model: 'CX-5 Signature',
    year: 2023,
    price: 5400000,
    mileage: '16,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Gray',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Mazda', 'CX-5', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights'],
    description: 'Sophisticated Mazda CX-5 with premium interior and engaging driving dynamics.',
    engineSize: '2.5L Turbo',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-12-09',
  },
  {
    id: 'v013',
    make: 'Mazda',
    model: 'CX-9 Grand Touring',
    year: 2022,
    price: 6200000,
    mileage: '21,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Blue',
    condition: 'Foreign Used',
    location: 'Kisumu',
    images: generateVehicleImages('Mazda', 'CX-9', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Parking Sensors', 'Heated Seats'],
    description: 'Spacious Mazda CX-9 with three-row seating and luxury features throughout.',
    engineSize: '2.5L Turbo',
    drivetrain: 'AWD',
    seats: 7,
    doors: 4,
    createdAt: '2024-12-08',
  },

  // Subaru Lineup
  {
    id: 'v014',
    make: 'Subaru',
    model: 'Forester XT',
    year: 2023,
    price: 4900000,
    mileage: '19,000 km',
    transmission: 'CVT',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Green',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Subaru', 'Forester', 4),
    features: ['Navigation System', 'Backup Camera', 'Alloy Wheels', 'Cruise Control'],
    description: 'Reliable Subaru Forester with legendary AWD system and excellent safety ratings.',
    engineSize: '2.0L Turbo',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-12-07',
  },
  {
    id: 'v015',
    make: 'Subaru',
    model: 'Outback Wilderness',
    year: 2022,
    price: 5600000,
    mileage: '25,000 km',
    transmission: 'CVT',
    fuelType: 'Petrol',
    bodyType: 'Wagon',
    color: 'Black',
    condition: 'Foreign Used',
    location: 'Nakuru',
    images: generateVehicleImages('Subaru', 'Outback', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights'],
    description: 'Adventure-ready Subaru Outback Wilderness with increased ground clearance.',
    engineSize: '2.4L Turbo',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-12-06',
  },

  // Audi Lineup
  {
    id: 'v016',
    make: 'Audi',
    model: 'Q7 55 TFSI',
    year: 2023,
    price: 13500000,
    mileage: '8,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Black',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Audi', 'Q7', 5),
    badges: ['LIMITED'],
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Parking Sensors', 'Heated Seats', 'LED Headlights', 'Keyless Entry'],
    description: 'Luxurious Audi Q7 with cutting-edge technology and refined performance.',
    engineSize: '3.0L V6 Turbo',
    drivetrain: 'Quattro AWD',
    seats: 7,
    doors: 4,
    createdAt: '2024-12-05',
  },
  {
    id: 'v017',
    make: 'Audi',
    model: 'Q5 45 TFSI',
    year: 2022,
    price: 8900000,
    mileage: '17,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'White',
    condition: 'Foreign Used',
    location: 'Mombasa',
    images: generateVehicleImages('Audi', 'Q5', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights'],
    description: 'Sleek Audi Q5 combining sporty handling with premium comfort.',
    engineSize: '2.0L Turbo',
    drivetrain: 'Quattro AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-12-04',
  },

  // Volkswagen Lineup
  {
    id: 'v018',
    make: 'Volkswagen',
    model: 'Tiguan R-Line',
    year: 2023,
    price: 5700000,
    mileage: '13,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Gray',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Volkswagen', 'Tiguan', 4),
    features: ['Navigation System', 'Backup Camera', 'Alloy Wheels', 'Bluetooth', 'Cruise Control'],
    description: 'Stylish VW Tiguan R-Line with sporty design and practical features.',
    engineSize: '2.0L Turbo',
    drivetrain: '4Motion AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-12-03',
  },
  {
    id: 'v019',
    make: 'Volkswagen',
    model: 'Touareg V6',
    year: 2022,
    price: 9800000,
    mileage: '20,000 km',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    bodyType: 'SUV',
    color: 'Blue',
    condition: 'Foreign Used',
    location: 'Kisumu',
    images: generateVehicleImages('Volkswagen', 'Touareg', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Parking Sensors', 'Heated Seats'],
    description: 'Premium VW Touareg with powerful diesel engine and luxury amenities.',
    engineSize: '3.0L V6 Diesel',
    drivetrain: '4Motion AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-12-02',
  },

  // Lexus Lineup
  {
    id: 'v020',
    make: 'Lexus',
    model: 'RX 350 F Sport',
    year: 2023,
    price: 11500000,
    mileage: '10,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Silver',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Lexus', 'RX', 5),
    badges: ['HOT DEAL'],
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Parking Sensors', 'Heated Seats', 'LED Headlights', 'Keyless Entry'],
    description: 'Luxurious Lexus RX 350 F Sport with exceptional build quality and refinement.',
    engineSize: '3.5L V6',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-12-01',
  },
  {
    id: 'v021',
    make: 'Lexus',
    model: 'LX 570',
    year: 2022,
    price: 16500000,
    mileage: '15,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Black',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Lexus', 'LX', 5),
    badges: ['LIMITED'],
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Parking Sensors', 'Heated Seats', 'Cruise Control', 'LED Headlights', 'Keyless Entry', 'Alloy Wheels'],
    description: 'Flagship Lexus LX 570 combining luxury, comfort, and off-road capability.',
    engineSize: '5.7L V8',
    drivetrain: '4WD',
    seats: 7,
    doors: 4,
    createdAt: '2024-11-30',
  },

  // Land Rover Lineup
  {
    id: 'v022',
    make: 'Land Rover',
    model: 'Range Rover Sport',
    year: 2023,
    price: 14200000,
    mileage: '7,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'White',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Land-Rover', 'Range-Rover-Sport', 5),
    badges: ['NEW'],
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Parking Sensors', 'Heated Seats', 'LED Headlights', 'Keyless Entry', 'Alloy Wheels'],
    description: 'Stunning Range Rover Sport with dynamic performance and ultimate luxury.',
    engineSize: '3.0L Inline-6 Turbo',
    drivetrain: '4WD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-29',
  },
  {
    id: 'v023',
    make: 'Land Rover',
    model: 'Discovery Sport',
    year: 2022,
    price: 7800000,
    mileage: '22,000 km',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    bodyType: 'SUV',
    color: 'Gray',
    condition: 'Foreign Used',
    location: 'Mombasa',
    images: generateVehicleImages('Land-Rover', 'Discovery-Sport', 4),
    features: ['Leather Seats', 'Navigation System', 'Backup Camera', 'Alloy Wheels', 'Bluetooth'],
    description: 'Versatile Land Rover Discovery Sport perfect for family adventures.',
    engineSize: '2.0L Diesel',
    drivetrain: '4WD',
    seats: 7,
    doors: 4,
    createdAt: '2024-11-28',
  },

  // Jeep Lineup
  {
    id: 'v024',
    make: 'Jeep',
    model: 'Wrangler Rubicon',
    year: 2023,
    price: 8500000,
    mileage: '11,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Green',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Jeep', 'Wrangler', 4),
    badges: ['LIMITED'],
    features: ['Navigation System', 'Backup Camera', 'LED Headlights', 'Alloy Wheels', 'Removable Top'],
    description: 'Iconic Jeep Wrangler Rubicon with legendary off-road capability.',
    engineSize: '3.6L V6',
    drivetrain: '4WD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-27',
  },
  {
    id: 'v025',
    make: 'Jeep',
    model: 'Grand Cherokee Limited',
    year: 2022,
    price: 7200000,
    mileage: '18,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Black',
    condition: 'Foreign Used',
    location: 'Nakuru',
    images: generateVehicleImages('Jeep', 'Grand-Cherokee', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Heated Seats'],
    description: 'Refined Jeep Grand Cherokee with upscale interior and smooth ride.',
    engineSize: '3.6L V6',
    drivetrain: '4WD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-26',
  },

  // Ford Lineup
  {
    id: 'v026',
    make: 'Ford',
    model: 'Ranger Raptor',
    year: 2023,
    price: 7500000,
    mileage: '14,000 km',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    bodyType: 'Pickup',
    color: 'Blue',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Ford', 'Ranger-Raptor', 4),
    badges: ['HOT DEAL'],
    features: ['Navigation System', 'Backup Camera', 'LED Headlights', 'Alloy Wheels', 'Cruise Control'],
    description: 'Performance-oriented Ford Ranger Raptor built for adventure.',
    engineSize: '2.0L Twin-Turbo Diesel',
    drivetrain: '4WD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-25',
  },
  {
    id: 'v027',
    make: 'Ford',
    model: 'Explorer Limited',
    year: 2022,
    price: 6900000,
    mileage: '19,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'White',
    condition: 'Foreign Used',
    location: 'Eldoret',
    images: generateVehicleImages('Ford', 'Explorer', 4),
    features: ['Leather Seats', 'Navigation System', 'Backup Camera', 'Heated Seats', 'Cruise Control'],
    description: 'Spacious Ford Explorer with comfortable seating for seven.',
    engineSize: '3.5L V6',
    drivetrain: 'AWD',
    seats: 7,
    doors: 4,
    createdAt: '2024-11-24',
  },

  // Mitsubishi Lineup
  {
    id: 'v028',
    make: 'Mitsubishi',
    model: 'Pajero Sport',
    year: 2023,
    price: 5300000,
    mileage: '16,000 km',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    bodyType: 'SUV',
    color: 'Silver',
    condition: 'Foreign Used',
    location: 'Mombasa',
    images: generateVehicleImages('Mitsubishi', 'Pajero-Sport', 4),
    features: ['Backup Camera', 'Alloy Wheels', 'Bluetooth', 'Cruise Control'],
    description: 'Rugged Mitsubishi Pajero Sport perfect for Kenyan terrain.',
    engineSize: '2.4L Diesel',
    drivetrain: '4WD',
    seats: 7,
    doors: 4,
    createdAt: '2024-11-23',
  },
  {
    id: 'v029',
    make: 'Mitsubishi',
    model: 'Outlander PHEV',
    year: 2022,
    price: 4700000,
    mileage: '23,000 km',
    transmission: 'CVT',
    fuelType: 'Plug-in Hybrid',
    bodyType: 'SUV',
    color: 'Red',
    condition: 'Foreign Used',
    location: 'Kisumu',
    images: generateVehicleImages('Mitsubishi', 'Outlander', 4),
    features: ['Navigation System', 'Backup Camera', 'LED Headlights', 'Alloy Wheels'],
    description: 'Eco-friendly Mitsubishi Outlander PHEV with impressive fuel economy.',
    engineSize: '2.4L Plug-in Hybrid',
    drivetrain: 'AWD',
    seats: 7,
    doors: 4,
    createdAt: '2024-11-22',
  },

  // Hyundai Lineup
  {
    id: 'v030',
    make: 'Hyundai',
    model: 'Tucson Limited',
    year: 2023,
    price: 4900000,
    mileage: '12,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Blue',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Hyundai', 'Tucson', 4),
    features: ['Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights', 'Cruise Control'],
    description: 'Modern Hyundai Tucson with advanced safety features and sleek design.',
    engineSize: '2.5L',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-21',
  },
  {
    id: 'v031',
    make: 'Hyundai',
    model: 'Santa Fe Calligraphy',
    year: 2022,
    price: 6100000,
    mileage: '17,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Gray',
    condition: 'Foreign Used',
    location: 'Nakuru',
    images: generateVehicleImages('Hyundai', 'Santa-Fe', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Heated Seats', 'Parking Sensors'],
    description: 'Premium Hyundai Santa Fe Calligraphy with luxury appointments.',
    engineSize: '2.5L Turbo',
    drivetrain: 'AWD',
    seats: 7,
    doors: 4,
    createdAt: '2024-11-20',
  },

  // Kia Lineup
  {
    id: 'v032',
    make: 'Kia',
    model: 'Sportage GT-Line',
    year: 2023,
    price: 4600000,
    mileage: '13,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Black',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Kia', 'Sportage', 4),
    features: ['Navigation System', 'Backup Camera', 'LED Headlights', 'Alloy Wheels', 'Bluetooth'],
    description: 'Stylish Kia Sportage GT-Line with excellent value and features.',
    engineSize: '2.0L Turbo',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-19',
  },
  {
    id: 'v033',
    make: 'Kia',
    model: 'Sorento SX',
    year: 2022,
    price: 5800000,
    mileage: '18,000 km',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    bodyType: 'SUV',
    color: 'White',
    condition: 'Foreign Used',
    location: 'Mombasa',
    images: generateVehicleImages('Kia', 'Sorento', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Heated Seats'],
    description: 'Family-friendly Kia Sorento with spacious interior and modern tech.',
    engineSize: '2.2L Diesel',
    drivetrain: 'AWD',
    seats: 7,
    doors: 4,
    createdAt: '2024-11-18',
  },

  // Chevrolet Lineup
  {
    id: 'v034',
    make: 'Chevrolet',
    model: 'Tahoe LT',
    year: 2023,
    price: 9200000,
    mileage: '9,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Black',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Chevrolet', 'Tahoe', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Heated Seats', 'Third Row'],
    description: 'Full-size Chevrolet Tahoe with commanding presence and luxury features.',
    engineSize: '5.3L V8',
    drivetrain: '4WD',
    seats: 8,
    doors: 4,
    createdAt: '2024-11-17',
  },
  {
    id: 'v035',
    make: 'Chevrolet',
    model: 'Trailblazer Premier',
    year: 2022,
    price: 5200000,
    mileage: '20,000 km',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    bodyType: 'SUV',
    color: 'Silver',
    condition: 'Foreign Used',
    location: 'Eldoret',
    images: generateVehicleImages('Chevrolet', 'Trailblazer', 4),
    features: ['Leather Seats', 'Navigation System', 'Backup Camera', 'Alloy Wheels', 'Cruise Control'],
    description: 'Capable Chevrolet Trailblazer with strong diesel engine.',
    engineSize: '2.8L Diesel',
    drivetrain: '4WD',
    seats: 7,
    doors: 4,
    createdAt: '2024-11-16',
  },

  // Peugeot Lineup
  {
    id: 'v036',
    make: 'Peugeot',
    model: '3008 GT',
    year: 2022,
    price: 4300000,
    mileage: '21,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Gray',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Peugeot', '3008', 4),
    features: ['Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights', 'Alloy Wheels'],
    description: 'Distinctive Peugeot 3008 GT with unique design and i-Cockpit interior.',
    engineSize: '1.6L Turbo',
    drivetrain: 'FWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-15',
  },
  {
    id: 'v037',
    make: 'Peugeot',
    model: '5008 GT',
    year: 2021,
    price: 4800000,
    mileage: '28,000 km',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    bodyType: 'SUV',
    color: 'Blue',
    condition: 'Foreign Used',
    location: 'Kisumu',
    images: generateVehicleImages('Peugeot', '5008', 4),
    features: ['Navigation System', 'Backup Camera', 'Alloy Wheels', 'Bluetooth', 'Third Row'],
    description: 'Versatile Peugeot 5008 with seven-seat configuration.',
    engineSize: '2.0L Diesel',
    drivetrain: 'FWD',
    seats: 7,
    doors: 4,
    createdAt: '2024-11-14',
  },

  // Additional Mercedes-Benz
  {
    id: 'v038',
    make: 'Mercedes-Benz',
    model: 'GLE 450',
    year: 2023,
    price: 14800000,
    mileage: '6,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'White',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Mercedes', 'GLE', 5),
    badges: ['NEW'],
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Parking Sensors', 'Heated Seats', 'LED Headlights', 'Keyless Entry', 'Alloy Wheels', 'Cruise Control'],
    description: 'Refined Mercedes-Benz GLE 450 with advanced MBUX system and luxurious cabin.',
    engineSize: '3.0L Inline-6 Turbo',
    drivetrain: '4MATIC AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-13',
  },
  {
    id: 'v039',
    make: 'Mercedes-Benz',
    model: 'GLC 300',
    year: 2022,
    price: 9600000,
    mileage: '14,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Silver',
    condition: 'Foreign Used',
    location: 'Mombasa',
    images: generateVehicleImages('Mercedes', 'GLC', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights'],
    description: 'Compact luxury Mercedes-Benz GLC 300 with sporty handling.',
    engineSize: '2.0L Turbo',
    drivetrain: '4MATIC AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-12',
  },

  // Additional BMW
  {
    id: 'v040',
    make: 'BMW',
    model: 'X5 xDrive40i',
    year: 2023,
    price: 13200000,
    mileage: '7,500 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Blue',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('BMW', 'X5', 5),
    badges: ['HOT DEAL'],
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'Parking Sensors', 'Heated Seats', 'LED Headlights', 'Cruise Control'],
    description: 'Dynamic BMW X5 with perfect blend of performance and luxury.',
    engineSize: '3.0L Inline-6 Turbo',
    drivetrain: 'xDrive AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-11',
  },
  {
    id: 'v041',
    make: 'BMW',
    model: 'X3 xDrive30i',
    year: 2022,
    price: 8200000,
    mileage: '16,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'Black',
    condition: 'Foreign Used',
    location: 'Nakuru',
    images: generateVehicleImages('BMW', 'X3', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights'],
    description: 'Agile BMW X3 combining practicality with driving pleasure.',
    engineSize: '2.0L Turbo',
    drivetrain: 'xDrive AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-10',
  },

  // Sedans - Toyota
  {
    id: 'v042',
    make: 'Toyota',
    model: 'Camry Hybrid XLE',
    year: 2023,
    price: 5600000,
    mileage: '11,000 km',
    transmission: 'CVT',
    fuelType: 'Hybrid',
    bodyType: 'Sedan',
    color: 'Silver',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Toyota', 'Camry', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights', 'Cruise Control'],
    description: 'Refined Toyota Camry Hybrid with excellent fuel economy and comfort.',
    engineSize: '2.5L Hybrid',
    drivetrain: 'FWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-09',
  },
  {
    id: 'v043',
    make: 'Toyota',
    model: 'Mark X 250G',
    year: 2021,
    price: 3200000,
    mileage: '35,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    color: 'Black',
    condition: 'Foreign Used',
    location: 'Eldoret',
    images: generateVehicleImages('Toyota', 'Mark-X', 4),
    features: ['Leather Seats', 'Alloy Wheels', 'Bluetooth', 'Cruise Control'],
    description: 'Sporty Toyota Mark X with rear-wheel drive dynamics.',
    engineSize: '2.5L V6',
    drivetrain: 'RWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-08',
  },

  // Sedans - Honda
  {
    id: 'v044',
    make: 'Honda',
    model: 'Accord Touring',
    year: 2023,
    price: 5400000,
    mileage: '12,000 km',
    transmission: 'CVT',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    color: 'White',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Honda', 'Accord', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights', 'Heated Seats'],
    description: 'Sophisticated Honda Accord Touring with premium features.',
    engineSize: '1.5L Turbo',
    drivetrain: 'FWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-07',
  },
  {
    id: 'v045',
    make: 'Honda',
    model: 'Civic Type R',
    year: 2022,
    price: 6800000,
    mileage: '8,000 km',
    transmission: 'Manual',
    fuelType: 'Petrol',
    bodyType: 'Hatchback',
    color: 'Red',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Honda', 'Civic', 4),
    badges: ['LIMITED'],
    features: ['Sport Seats', 'Navigation System', 'Backup Camera', 'LED Headlights', 'Alloy Wheels', 'Performance Exhaust'],
    description: 'High-performance Honda Civic Type R for enthusiasts.',
    engineSize: '2.0L Turbo',
    drivetrain: 'FWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-06',
  },

  // Sedans - Mazda
  {
    id: 'v046',
    make: 'Mazda',
    model: 'Mazda6 Signature',
    year: 2022,
    price: 4200000,
    mileage: '19,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    color: 'Gray',
    condition: 'Foreign Used',
    location: 'Mombasa',
    images: generateVehicleImages('Mazda', 'Mazda6', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights'],
    description: 'Elegant Mazda6 Signature with upscale interior and Skyactiv technology.',
    engineSize: '2.5L Turbo',
    drivetrain: 'FWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-05',
  },
  {
    id: 'v047',
    make: 'Mazda',
    model: 'Axela Sport',
    year: 2021,
    price: 2800000,
    mileage: '31,000 km',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    bodyType: 'Hatchback',
    color: 'Blue',
    condition: 'Foreign Used',
    location: 'Kisumu',
    images: generateVehicleImages('Mazda', 'Axela', 4),
    features: ['Navigation System', 'Backup Camera', 'Alloy Wheels', 'Bluetooth'],
    description: 'Sporty Mazda Axela (Mazda3) with engaging driving experience.',
    engineSize: '2.0L',
    drivetrain: 'FWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-04',
  },

  // Sedans - Subaru
  {
    id: 'v048',
    make: 'Subaru',
    model: 'Legacy GT',
    year: 2022,
    price: 4500000,
    mileage: '17,000 km',
    transmission: 'CVT',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    color: 'Black',
    condition: 'Foreign Used',
    location: 'Nairobi',
    images: generateVehicleImages('Subaru', 'Legacy', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights', 'EyeSight Safety'],
    description: 'Well-equipped Subaru Legacy GT with standard AWD and EyeSight.',
    engineSize: '2.4L Turbo',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-03',
  },
  {
    id: 'v049',
    make: 'Subaru',
    model: 'WRX STI',
    year: 2021,
    price: 5900000,
    mileage: '22,000 km',
    transmission: 'Manual',
    fuelType: 'Petrol',
    bodyType: 'Sedan',
    color: 'Blue',
    condition: 'Foreign Used',
    location: 'Nakuru',
    images: generateVehicleImages('Subaru', 'WRX', 4),
    badges: ['LIMITED'],
    features: ['Sport Seats', 'Navigation System', 'Backup Camera', 'Alloy Wheels', 'Performance Brakes'],
    description: 'Iconic Subaru WRX STI with legendary performance and AWD capability.',
    engineSize: '2.5L Turbo Boxer',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-02',
  },

  // Additional Nissan
  {
    id: 'v050',
    make: 'Nissan',
    model: 'Rogue SL',
    year: 2022,
    price: 4100000,
    mileage: '20,000 km',
    transmission: 'CVT',
    fuelType: 'Petrol',
    bodyType: 'SUV',
    color: 'White',
    condition: 'Foreign Used',
    location: 'Eldoret',
    images: generateVehicleImages('Nissan', 'Rogue', 4),
    features: ['Leather Seats', 'Sunroof', 'Navigation System', 'Backup Camera', 'LED Headlights'],
    description: 'Comfortable Nissan Rogue SL with advanced safety features.',
    engineSize: '2.5L',
    drivetrain: 'AWD',
    seats: 5,
    doors: 4,
    createdAt: '2024-11-01',
  },
];

// Helper functions for filtering and sorting
export const getFeaturedVehicles = (): Vehicle[] => {
  return mockVehicles.filter(v => v.featured).slice(0, 5);
};

export const getNewArrivals = (): Vehicle[] => {
  return mockVehicles
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, 8);
};

export const getHotDeals = (): Vehicle[] => {
  return mockVehicles
    .filter(v => v.badges?.includes('HOT DEAL'))
    .slice(0, 6);
};

export const getVehicleById = (id: string): Vehicle | undefined => {
  return mockVehicles.find(v => v.id === id);
};
